name: dsci310proj
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel=7.1
  - pandas=3.0
  - requests=2.32.5
  - matplotlib=3.10.8
  - numpy=2.4.2
  - scipy=1.17.0
  - seaborn=0.13.2
  - scikit-learn=1.8.0
  - conda-lock=4.0
  - jupyterlab